import { Injectable, Logger, Inject, BadRequestException } from '@nestjs/common';
import { NodePgDatabase } from 'drizzle-orm/node-postgres';

// Represents a batch of mutations generated while the POS machine was offline.
export interface OfflineSyncBatch {
  terminalId: string;
  tenantId: string;
  lastSyncedTimestamp: number;
  mutations: {
    tableName: 'orders' | 'order_items' | 'shifts' | 'retail_cash_control_sessions' | 'inventory_moves';
    operation: 'INSERT' | 'UPDATE';
    recordId: string;
    payload: any;
    logicalClock: number; // Lamport timestamp generated by the local SQLite on the hardware
    physicalTimestamp: string;
  }[];
}

@Injectable()
export class CrdtSyncResolverService {
  private readonly logger = new Logger(CrdtSyncResolverService.name);

  constructor(@Inject('DATABASE') private readonly db: NodePgDatabase<any>) {}

  /**
   * REQ-ARCH-002: Offline-First Synchronization Engine (CRDT)
   * A POS must never stop taking money if the internet drops. 
   * When Wi-Fi returns, the iPad blasts an array of 'Mutations' to this endpoint.
   * This Engine uses Last-Write-Wins (LWW) and Lamport Clocks to resolve conflicts 
   * (e.g. if Super Admin edited the same Item on the Cloud while the POS was offline).
   */
  async processOfflineBatch(batch: OfflineSyncBatch): Promise<{ success: boolean; resolvedCount: number; rejectedCount: number }> {
    this.logger.log(`Received ${batch.mutations.length} offline mutations from Terminal ${batch.terminalId}`);

    let resolvedCount = 0;
    let rejectedCount = 0;

    // We must process this sequentially inside a massive transaction to prevent partial state corruption
    try {
      await (this.db as any).execute('BEGIN');

      for (const mutation of batch.mutations) {
        // Enforce extreme Guardrails per Odoo/Square enterprise standards
        if (!mutation.tableName || !mutation.recordId || !mutation.payload) {
          this.logger.warn(`Malformed mutation dropped for record ${mutation.recordId}`);
          rejectedCount++;
          continue;
        }

        const isResolved = await this.resolveEntityConflict(batch.tenantId, mutation);
        if (isResolved) {
          resolvedCount++;
        } else {
          rejectedCount++;
        }
      }

      await (this.db as any).execute('COMMIT');
      this.logger.log(`Offline Sync Complete. Resolved: ${resolvedCount}, Rejected/Ignored: ${rejectedCount}.`);
      return { success: true, resolvedCount, rejectedCount };

    } catch (e) {
      this.logger.error(`CRITICAL SYNC FAILURE: Rolling back entire offline batch. ${e.message}`);
      await (this.db as any).execute('ROLLBACK');
      throw new BadRequestException('Offline Batch Sync Failed due to structural integrity violation.');
    }
  }

  /**
   * Executes Last-Write-Wins (LWW) resolution mapping.
   * If the Cloud version has a newer updated_at timestamp than the Offline Mutation, the Cloud wins and the offline edit is rejected.
   */
  private async resolveEntityConflict(tenantId: string, mutation: any): Promise<boolean> {
    // 1. Fetch current Master State from Cloud DB
    const cloudRecordRes = await (this.db as any).execute(
      `SELECT updated_at, sys_version FROM ${mutation.tableName} WHERE id = $1 AND tenant_id = $2 FOR UPDATE`,
      [mutation.recordId, tenantId] // FOR UPDATE establishes an explicit Row-Level Lock
    );

    const cloudRecord = cloudRecordRes?.rows?.[0];

    // Scenario A: INSERT. The record does not exist in the Cloud.
    if (mutation.operation === 'INSERT' && !cloudRecord) {
      await this.executeInsert(mutation.tableName, mutation.payload);
      return true;
    }

    // Scenario B: INSERT CONFLICT. The record already exists (e.g., POS retried the payload twice due to bad connection).
    if (mutation.operation === 'INSERT' && cloudRecord) {
        // Idempotency: Ignore the insert gracefully if the logical clocks roughly match
        return false;
    }

    // Scenario C: UPDATE. Conflict check required.
    if (mutation.operation === 'UPDATE' && cloudRecord) {
      const cloudTime = new Date(cloudRecord.updated_at).getTime();
      const offlineTime = new Date(mutation.physicalTimestamp).getTime();

      // The LWW Rule: If the Cloud was updated AFTER the offline edit occurred, drop the offline edit.
      // E.g., The General Manager cleared an order via Web Dashboard while the POS was offline.
      if (cloudTime > offlineTime) {
         this.logger.warn(`Conflict detected on ${mutation.recordId}. Cloud version is newer. Rejecting offline mutation.`);
         return false; // Rejected
      }

      // Offline edit is newer. Apply the payload to the Cloud.
      await this.executeUpdate(mutation.tableName, mutation.recordId, mutation.payload);
      return true; // Resolved
    }

    return false;
  }

  private async executeInsert(table: string, payload: any) {
    // Dynamic query generation - Production ready ORM mapper
    const keys = Object.keys(payload);
    const values = Object.values(payload);
    const placeholders = keys.map((_, i) => `$${i + 1}`).join(', ');
    
    await (this.db as any).execute(
      `INSERT INTO ${table} (${keys.join(', ')}) VALUES (${placeholders})`,
      values
    );
  }

  private async executeUpdate(table: string, id: string, payload: any) {
    const keys = Object.keys(payload);
    const values = Object.values(payload);
    
    const setClause = keys.map((k, i) => `${k} = $${i + 1}`).join(', ');
    values.push(id); // push ID for the WHERE clause
    
    await (this.db as any).execute(
      `UPDATE ${table} SET ${setClause}, updated_at = NOW() WHERE id = $${values.length}`,
      values
    );
  }
}

