export enum LoyaltyTransactionType {
  EARN_POINTS = 'EARN_POINTS',
  REDEEM_POINTS = 'REDEEM_POINTS',
  ADJUSTMENT = 'ADJUSTMENT',
  EXPIRATION = 'EXPIRATION',
  TRANSFER = 'TRANSFER',
  REFUND = 'REFUND',
  BONUS = 'BONUS',
  CANCELLATION = 'CANCELLATION',
}
