import { StorefrontProps } from '../../../types/storefront';

export const storefrontConfig: StorefrontProps = {
  name: 'House of Biryani',
  tenantType: 'Restaurant',
  tagline: 'Authentic Hyderabadi Dum Biryani · Chicago, IL',
  description:
    'Famous for our signature slow-cooked Dum Biryani, rich Haleem, Paan, and full catering services. Serving Chicago\'s Devon Avenue since 2008.',
  heroImageUrl:
    'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1600&q=80',
  accentColor: '#8B0000',
  accentTextColor: '#ffffff',
  highlightColor: '#F59E0B',
  headlineTemplate: 'Authentic Hyderabadi Flavors for [Name]',
  cartLabel: 'Cart',
  navLinks: [
    { label: 'Home', href: '/restaurant/house-of-biryani' },
    { label: 'Paan Menu', href: '/restaurant/house-of-biryani/menu?cat=paan' },
    { label: 'Full Menu', href: '/restaurant/house-of-biryani/menu' },
    { label: 'Catering', href: '/restaurant/house-of-biryani/catering' },
  ],
  primaryCTA: { label: 'Order Online', href: '/restaurant/house-of-biryani/menu' },
  promo: {
    badge: '🍽️ CATERING AVAILABLE · 72-HR NOTICE REQUIRED',
    headline: 'Hosting an Event? Let Us Handle the Food.',
    body: 'Full and half-tray catering for Mutton Biryani, Goat Haleem, Chicken-65, Chicken Manchurian, and Vegetable Biryani. 50% deposit on order, full payment before delivery.',
    cta1: { label: 'View Catering Menu', href: '/restaurant/house-of-biryani/catering' },
    cta2: { label: 'See Full Menu', href: '/restaurant/house-of-biryani/menu' },
  },
  carousel: [
    {
      icon: '🍛',
      title: 'Authentic Dum Biryani',
      subtitle: 'Signature Hero',
      desc: 'Traditional slow-cooked Goat, Chicken, or Veg Dum Biryani — the taste of Hyderabad.',
      href: '/restaurant/house-of-biryani/menu?cat=biryani',
      imageUrl: 'https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_150,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_150/ouwa84pht8n8yg2u36qq',
    },
    {
      icon: '🍃',
      title: 'Premium Paan Bar',
      subtitle: '16 Varieties',
      desc: 'Famous Sarda Ka Paan, Sweet Paan, and Navratan — prepared live to your liking.',
      href: '/restaurant/house-of-biryani/menu?cat=paan',
      imageUrl: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=800&q=80',
    },
    {
      icon: '🥘',
      title: 'Heritage Haleem',
      subtitle: 'Slow-Cooked',
      desc: 'Rich, stew-like delicacy made with pounded wheat and tender meat, cooked for 12 hours.',
      href: '/restaurant/house-of-biryani/menu?cat=haleem',
      imageUrl: 'https://images.unsplash.com/photo-1631481920803-057d29fe96f6?auto=format&fit=crop&w=800&q=80',
    },
    {
      icon: '🍗',
      title: 'Chicken 65',
      subtitle: 'Spicy Appetizer',
      desc: 'Deep-fried, tempered with curry leaves and green chillies. A Hyderabadi classic.',
      href: '/restaurant/house-of-biryani/menu?cat=appetizers',
      imageUrl: 'https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=800&q=80',
    },
    {
      icon: '🥡',
      title: 'Catering Platters',
      subtitle: 'Events & Parties',
      desc: 'Full and half trays for your gatherings. 72-hr notice and local delivery available.',
      href: '/restaurant/house-of-biryani/catering',
      imageUrl: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=800&q=80',
    },
  ],
  address: '2306 W Devon Ave, Chicago, IL 60659',
  phone: '(773) 465-2455',
  email: 'orders@houseofbiryanirestaurant.com',
  specialty: 'Paan',
  botName: 'Restaurant Bot', // Keeping for type safety but it will be dynamic in layout
  botKnowledge: {
    businessName: 'House of Biryani',
    description: 'Authentic Hyderabadi restaurant at 2306 W Devon Ave, Chicago. Famous for 12-hour slow-cooked Dum Biryani and a 16-variety Paan Bar.',
    halal: true,
    address: '2306 W Devon Ave, Chicago, IL 60659',
    phone: '(773) 465-2455',
    hours: 'Mon–Thu 11 AM–10 PM · Fri–Sat 11 AM–11 PM · Sun 11 AM–10 PM',
    menuHighlights: ['Mutton Dum Biryani', 'Goat Haleem', 'Sarda Ka Paan', 'Chicken 65', 'Fish Biryani', 'Paneer Biryani'],
    specialties: ['biryani', 'haleem', 'paan', 'chicken 65', 'nihari', 'halal'],
    cateringInfo: 'We offer full & half-tray catering for events. Items include Mutton Biryani, Goat Haleem, Chicken-65, Chicken Manchurian & Veg Biryani. Minimum 72-hour advance notice required. 50% deposit on order. Call (773) 465-2455 to book.',
    faqs: [
      { q: 'Is the food halal?', a: 'Yes! 100% HMS-certified Halal. All meat is sourced from Halal-certified suppliers. 🌙' },
      { q: 'Do you deliver?', a: 'Yes, we offer local delivery through our online ordering system and via DoorDash/UberEats.' },
      { q: 'What is dum biryani?', a: 'Dum Biryani is a slow-cooking method where meat and rice are sealed in a pot over low heat for several hours — incredibly tender meat and aromatic rice.' },
      { q: 'What paan do you have?', a: 'We offer 16 Paan varieties including Sarda Ka Paan, Sweet Paan, Meetha Paan, Navratan Paan, Chocolate Paan, and seasonal specials! 🍃' },
      { q: 'Do you cater weddings?', a: 'Absolutely! We specialize in South Asian wedding catering. Full and half trays available with 72-hour advance notice. Call us at (773) 465-2455.' },
    ],
  },
  allowSearch: true,
  theme: 'MINIMALIST_ARTISANAL',
};
