/**
 * â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
 * PROJECT:      paysurity-platform-2026
 * REQUIREMENT:  ORC-009 â€” Daily Settlement Processing
 * FILE TYPE:    DTO
 * MODULE:       settlement
 * PRIORITY:     P0
 * SOURCE:       Requirements/Canonical/ORC_PAYMENT_ORCHESTRATION.md
 * WORKER:       CODER-009
 * GENERATED:    2026-03-18T10:32:24.222Z
 * MANIFEST:     process.env.MANIFEST_FILE || 'REQUIREMENTS_V5_MANIFEST.json'
 * â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
 */
import { IsString, IsNumber, IsEnum, IsOptional, IsArray, IsDateString, IsUUID, IsNotEmpty, Min, ArrayNotEmpty } from 'class-validator';


export enum SettlementStatus {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
  COMPLETED = 'COMPLETED',
}

export enum SettlementType {
  DAILY = 'DAILY',
  BATCH = 'BATCH',
  ADHOC = 'ADHOC',
}

export class CreateSettlementDto {
  @IsUUID()
  @IsOptional() // ID is optional during creation, can be generated by service/DB
  id?: string;

  @IsDateString()
  @IsNotEmpty()
  settlementDate: string; // ISO 8601 date string (e.g., 'YYYY-MM-DD')

  @IsNumber()
  @Min(0)
  totalAmount: number;

  @IsString()
  @IsNotEmpty()
  currency: string; // e.g., 'USD', 'EUR'

  @IsEnum(SettlementStatus)
  @IsNotEmpty()
  status: SettlementStatus;

  @IsEnum(SettlementType)
  @IsNotEmpty()
  type: SettlementType;

  @IsDateString()
  @IsOptional()
  processedAt?: string; // ISO 8601 datetime string

  @IsArray()
  @IsString({ each: true })
  @ArrayNotEmpty()
  @IsOptional()
  transactionIds?: string[]; // IDs of transactions included in this settlement
}

export class UpdateSettlementDto extends (class {} as any) {}

export class ProcessSettlementDto {
  @IsDateString()
  @IsNotEmpty()
  settlementDate: string; // Date for which to process daily settlement (e.g., 'YYYY-MM-DD')
}

// DTO for returning settlement data to clients
// Note: TenantId is internal and should not be exposed directly in public APIs unless explicitly required.
export class SettlementResponseDto {
  @IsUUID()
  id: string;

  @IsString()
  settlementDate: string; // ISO 8601 date string

  @IsNumber()
  totalAmount: number;

  @IsString()
  currency: string;

  @IsEnum(SettlementStatus)
  status: SettlementStatus;

  @IsEnum(SettlementType)
  type: SettlementType;

  @IsOptional()
  @IsDateString()
  processedAt?: string;

  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  transactionIds?: string[];

  @IsDateString()
  createdAt: string;

  @IsDateString()
  updatedAt: string;
}


