import { StorefrontProps } from '../../../types/storefront';

export const storefrontConfig: StorefrontProps = {
  name: 'Tawakkul Restaurant',
  tenantType: 'Restaurant',
  tagline: 'HMS-Certified Halal · Pakistani & Indian · Hyderabadi',
  description:
    'From the streets of Hyderabad to Chicago. Legendary Dum Biryani, Karahi, Seekh Kebab and authentic street food — prepared with love and the finest halal ingredients.',
  heroImageUrl:
    'https://storage.googleapis.com/paysurity-assets/Tawakkul/hero.jpg',
  accentColor: '#1a472a',
  accentTextColor: '#ffffff',
  highlightColor: '#D4AF37',
  headlineTemplate: 'HMS-Certified Delights by [Name]',
  cartLabel: 'Cart',
  navLinks: [
    { label: 'Home', href: '/restaurant/tawakkul-restaurant' },
    { label: 'Menu', href: '/restaurant/tawakkul-restaurant/menu' },
    { label: 'Catering', href: '/restaurant/tawakkul-restaurant/catering' },
    { label: 'Order Online', href: '/restaurant/tawakkul-restaurant/order' },
  ],
  primaryCTA: { label: 'Order Online Now', href: '/restaurant/tawakkul-restaurant/order' },
  promo: {
    badge: '🌙 100% HMS-CERTIFIED HALAL · ALL MEATS',
    headline: 'Certified Halal. Authentically Pakistani.',
    body: 'Every dish at Tawakkul is prepared with HMS-certified halal ingredients, traditional Hyderabadi recipes and no shortcuts. Your trust is our most important ingredient.',
    cta1: { label: 'View Full Menu', href: '/restaurant/tawakkul-restaurant/menu' },
    cta2: { label: 'Catering Inquiry', href: '/restaurant/tawakkul-restaurant/catering' },
  },
  carousel: [
    {
      icon: '🍢',
      title: 'Lamb Chops',
      subtitle: 'HMS-Certified BBQ',
      desc: 'Grilled lamb chops marinated in house spices. 100% HMS-certified. $18.99',
      href: '/restaurant/tawakkul-restaurant/menu?cat=bbq',
      imageUrl: 'https://storage.googleapis.com/paysurity-assets/Tawakkul/lamb_chops.jpg',
    },
    {
      icon: '🍛',
      title: 'Malai Kebab',
      subtitle: 'Signature Grills',
      desc: 'Creamy grilled chicken kebabs. Authentic Hyderabadi flavor. $12.99',
      href: '/restaurant/tawakkul-restaurant/menu?cat=bbq',
      imageUrl: 'https://storage.googleapis.com/paysurity-assets/Tawakkul/malai_kebab.jpg',
    },
    {
      icon: '🥘',
      title: 'Desi Breakfast',
      subtitle: 'Weekend Specials',
      desc: 'Serving Nihari and Paya starting at 8 AM every Sat & Sun. Authentic tastes that feel like home.',
      href: '/restaurant/tawakkul-restaurant/menu?cat=breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    },
    {
      icon: '🔥',
      title: 'Karahi Junction',
      subtitle: 'Freshly Wok-Fired',
      desc: 'Goat and Chicken Karahis cooked live in a traditional wok with fresh tomatoes and ginger.',
      href: '/restaurant/tawakkul-restaurant/menu?cat=karahi',
      imageUrl: 'https://images.unsplash.com/photo-1601050633647-81a317112006?auto=format&fit=crop&w=800&q=80',
    },
    {
      icon: '🫓',
      title: 'Fresh Tandoor',
      subtitle: 'Baked to Order',
      desc: 'Garlic Naan, Roghni Naan, and authentic Parathas straight from our charcoal tandoor.',
      href: '/restaurant/tawakkul-restaurant/menu?cat=breads',
      imageUrl: 'https://images.unsplash.com/photo-1601356616077-6957284f729c?auto=format&fit=crop&w=800&q=80',
    },
  ],
  address: '6410 N Claremont Ave, Chicago, IL 60659',
  phone: '(773) 743-5555',
  email: 'info@tawakkulrestaurant.food',
  botName: 'Tawakkul Bot',
  botKnowledge: {
    businessName: 'Tawakkul Restaurant',
    description: 'Authentic Pakistani & Hyderabadi restaurant at 6410 N Claremont Ave, Chicago. Known for HMS-certified BBQ, Dum Biryani, Karahi, and a legendary weekend Desi Breakfast.',
    halal: true,
    address: '6410 N Claremont Ave, Chicago, IL 60659',
    phone: '(773) 743-5555',
    hours: 'Mon–Fri 11 AM–11 PM · Sat–Sun 8 AM–11 PM (Nihari & Paya from 8 AM on weekends)',
    menuHighlights: ['Goat Dum Biryani', 'Seekh Kebab', 'Chicken Karahi', 'Nihari', 'Paya', 'Garlic Naan'],
    specialties: ['biryani', 'karahi', 'seekh kebab', 'nihari', 'paya', 'bbq', 'halal'],
    cateringInfo: 'Tawakkul offers catering for weddings, corporate events, and family gatherings. We specialize in Dum Biryani, Karahi, and BBQ platters. Minimum 48-hour notice required. Call (773) 743-5555 for a quote.',
    faqs: [
      { q: 'Is everything halal?', a: 'Absolutely — every item at Tawakkul is 100% HMS-Certified Halal. We take halal compliance very seriously. 🌙' },
      { q: 'What time does breakfast start?', a: 'Our famous Desi Breakfast (Nihari & Paya) starts at 8 AM on Saturdays and Sundays only. Come early — it sells out fast!' },
      { q: 'Do you have parking?', a: 'Yes! Street parking is available on N Claremont Ave and surrounding streets. We\'re also accessible via CTA Red/Brown Line.' },
      { q: 'Do you take online orders?', a: 'Yes! You can order online via the "Order Online" button in our menu, or through DoorDash and UberEats.' },
      { q: 'What is Karahi?', a: 'Karahi is a traditional South Asian stir-fry cooked in a heavy wok (karahi) with fresh tomatoes, ginger, and spices. Our Goat Karahi is a customer favourite! 🔥' },
    ],
  },
  allowSearch: true,
  groupOrderLink: 'https://www.grubhub.com/restaurant/tawakkul-restaurant-6410-n-claremont-ave-chicago/332152',
  theme: 'VIBRANT_SPICE',
};
