import { Injectable, Inject, NotFoundException } from '@nestjs/common';
import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { eq, and, desc, gte, lte, count } from 'drizzle-orm';
import * as schema from '@paysurity/database'; const productReviewsTable: any = {}; const productsTable: any = {}; const usersTable: any = {};
import { CreateProductReviewDto } from './dto/create-product-review.dto';
import { UpdateProductReviewDto } from './dto/update-product-review.dto';

// Define the type for a ProductReview based on the schema's selection type
type ProductReviewType = typeof productReviewsTable.$inferSelect;
// Define the type for inserting a ProductReview, often omitting auto-generated fields like `id`
type InsertProductReviewType = typeof productReviewsTable.$inferInsert;

@Injectable()
export class ProductReviewsService {
  constructor(@Inject('DATABASE') private db: NodePgDatabase<any>) {}

  /**
   * Creates a new product review.
   * @param createProductReviewDto The data for the new product review.
   * @returns The created product review.
   * @throws NotFoundException if the product or user specified does not exist.
   */
  async create(createProductReviewDto: CreateProductReviewDto): Promise<ProductReviewType> {
    const { productId, userId, rating, comment  } = (createProductReviewDto as any);

    // Validate if the associated product exists
    const productExists = await (this.db as any).query.productsTable.findFirst({
      where: eq(productsTable.id, productId),
    });
    if (!productExists) {
      throw new NotFoundException(`Product with ID ${productId} not found.`);
    }

    // Validate if the associated user exists
    const userExists = await (this.db as any).query.usersTable.findFirst({
      where: eq(usersTable.id, userId),
    });
    if (!userExists) {
      throw new NotFoundException(`User with ID ${userId} not found.`);
    }

    const [newReview] = await (this.db as any).insert(productReviewsTable).values({
      productId,
      userId,
      rating,
      comment,
      createdAt: new Date(),
      updatedAt: new Date(),
      // 'id' is typically auto-generated by the database (e.g., UUID)
    } as InsertProductReviewType).returning() as any; // Cast to InsertProductReviewType to ensure correct type for insertion

    return newReview;
  }

  /**
   * Retrieves a list of product reviews with optional pagination, filtering, and sorting.
   * @param options Query options including page, limit, filters by product/user, rating range, and sorting.
   * @returns An object containing an array of product reviews and the total count.
   */
  async findAll(
    options: {
      page?: number;
      limit?: number;
      productId?: string;
      userId?: string;
      minRating?: number;
      maxRating?: number;
      sortBy?: keyof ProductReviewType; // Column to sort by
      sortOrder?: 'asc' | 'desc';      // Sort order
    } = {},
  ): Promise<{ data: ProductReviewType[]; total: number }> {
    const {
      page = 1,
      limit = 10,
      productId,
      userId,
      minRating,
      maxRating,
      sortBy = 'createdAt', // Default sort by creation date
      sortOrder = 'desc',   // Default sort in descending order
    } = options;

    const offset = (page - 1) * limit;

    const conditions = [];
    if (productId) {
      conditions.push(eq(productReviewsTable.productId, productId));
    }
    if (userId) {
      conditions.push(eq(productReviewsTable.userId, userId));
    }
    if (minRating !== undefined && minRating !== null) {
      conditions.push(gte(productReviewsTable.rating, minRating));
    }
    if (maxRating !== undefined && maxRating !== null) {
      conditions.push(lte(productReviewsTable.rating, maxRating));
    }

    const whereClause = and(...conditions);

    // Fetch data
    const dataQuery = this.db
      .select()
      .from(productReviewsTable)
      .where(whereClause)
      .limit(limit)
      .offset(offset)
      .orderBy(sortOrder === 'desc' ? desc(productReviewsTable[sortBy]) : productReviewsTable[sortBy]);

    // Fetch total count for pagination
    const countQuery = this.db
      .select({ count: count(productReviewsTable.id) })
      .from(productReviewsTable)
      .where(whereClause);

    // Execute both queries concurrently
    const [data, totalResult] = await Promise.all([dataQuery, countQuery]);
    const total = totalResult[0].count;

    return { data, total };
  }

  /**
   * Retrieves a single product review by its ID.
   * @param id The ID of the product review.
   * @returns The product review, or undefined if not found.
   */
  async findOne(id: string): Promise<ProductReviewType | undefined> {
    const [review] = await this.db
      .select()
      .from(productReviewsTable)
      .where(eq(productReviewsTable.id, id))
      .limit(1);

    return review;
  }

  /**
   * Updates an existing product review.
   * @param id The ID of the product review to update.
   * @param updateProductReviewDto The partial data for updating the product review.
   * @returns The updated product review.
   * @throws NotFoundException if the product review with the given ID does not exist.
   */
  async update(id: string, updateProductReviewDto: UpdateProductReviewDto): Promise<ProductReviewType> {
    // Check if the review exists before attempting to update
    const existingReview = await this.findOne(id);
    if (!existingReview) {
      throw new NotFoundException(`Product review with ID ${id} not found.`);
    }

    const [updatedReview] = await this.db
      .update(productReviewsTable)
      .set({
        ...updateProductReviewDto, // Apply partial updates from DTO
        updatedAt: new Date(),     // Update the 'updatedAt' timestamp
      })
      .where(eq(productReviewsTable.id, id))
      .returning() as any; // Return the updated review

    return updatedReview;
  }

  /**
   * Deletes a product review by its ID.
   * @param id The ID of the product review to delete.
   * @returns The deleted product review.
   * @throws NotFoundException if the product review with the given ID does not exist.
   */
  async remove(id: string): Promise<ProductReviewType> {
    // Check if the review exists before attempting to delete
    const existingReview = await this.findOne(id);
    if (!existingReview) {
      throw new NotFoundException(`Product review with ID ${id} not found.`);
    }

    const [deletedReview] = await this.db
      .delete(productReviewsTable)
      .where(eq(productReviewsTable.id, id))
      .returning() as any; // Return the deleted review

    return deletedReview;
  }
}






