import { Injectable, Logger, Inject } from '@nestjs/common';
import { EventBusService } from '../event-bus/event-bus.service';
import { sanitizeGatewayResponse } from '../../shared/utils/sanitize-gateway-response';

// Drizzle ORM Imports - Retained NodePgDatabase and sql for raw query execution
import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { sql } from 'drizzle-orm';

// For HttpService and RxJS conversion
import { HttpService } from '@nestjs/axios';

/**
 * PaySurity Internal Order and Order Item Schemas
 */
export interface PaySurityOrder {
  id?: string; // UUID, optional for new orders (generated by DB)
  tenantId: string;
  merchantId: string;
  externalOrderId: string; // Aggregator's order ID
  aggregator: 'DoorDash' | 'UberEats' | 'GrubHub' | string; // Union type for multiple aggregators
  status: 'PENDING' | 'ACCEPTED' | 'CANCELLED' | 'REFUNDED' | 'DELIVERED' | 'UNKNOWN';
  totalAmountCents: number;
  currency: string;
  createdAt?: Date;
  updatedAt?: Date;
  rawPayload: any;
  items: PaySurityOrderItem[];
}

export interface PaySurityOrderItem {
  id?: string; // UUID, optional for new items (generated by DB)
  orderId?: string; // Will be set when creating items related to an order
  tenantId: string;
  name: string;
  quantity: number;
  unitPriceCents: number;
  totalPriceCents: number;
}

@Injectable()
export class AggregatorService {
  private readonly logger = new Logger(AggregatorService.name);

  constructor(
    @Inject('DATABASE') private readonly db: NodePgDatabase<any>,
    private readonly eventBusService: EventBusService,
    private readonly httpService: HttpService,
  ) {}

  /**
   * Main entry point for processing incoming aggregator webhooks.
   * Handles idempotency, normalization, and persistence.
   */
  async processWebhook(aggregator: string, payload: any, tenantId: string, merchantId: string): Promise<string> {
    this.logger.log(`Processing ${aggregator} webhook for tenant ${tenantId}, merchant ${merchantId}`);
    try {
      // 1. Normalize the incoming payload to PaySurity's internal order format
      const normalizedOrder = this.normalizeOrder(aggregator, payload, tenantId, merchantId);

      // 2. Idempotency Check
      const existingOrder = await this.findExistingOrder(
        normalizedOrder.externalOrderId,
        normalizedOrder.aggregator,
        tenantId,
      );

      if (existingOrder) {
        this.logger.warn(
          `Order ${normalizedOrder.externalOrderId} already exists with status ${existingOrder.status}. Checking for updates.`,
        );

        // Check for status changes (e.g., a cancellation webhook for an existing order)
        if (normalizedOrder.status !== existingOrder.status) {
          this.logger.log(
            `Detected status change for order ${existingOrder.id}: ${existingOrder.status} -> ${normalizedOrder.status}. Updating...`,
          );
          await this.updateOrderStatus(
            existingOrder.id, // We have the internal ID now
            normalizedOrder.status,
            normalizedOrder.rawPayload,
            tenantId,
          );
          (this.eventBusService as any).emit('order.status.updated', {
            orderId: existingOrder.id,
            tenantId,
            merchantId,
            oldStatus: existingOrder.status,
            newStatus: normalizedOrder.status,
            externalOrderId: normalizedOrder.externalOrderId,
          });
          return existingOrder.id;
        }

        return existingOrder.id; // Return existing order ID
      }

      // 3. Persist new order
      const newOrderId = await this.createOrder(normalizedOrder);
      this.logger.log(`New order ${newOrderId} created for aggregator ${aggregator}.`);

      // 4. Emit event for further processing
      (this.eventBusService as any).emit('order.created', {
        orderId: newOrderId,
        tenantId,
        merchantId,
        aggregator: normalizedOrder.aggregator,
        externalOrderId: normalizedOrder.externalOrderId,
        totalAmountCents: normalizedOrder.totalAmountCents,
        status: normalizedOrder.status,
      });

      return newOrderId;
    } catch (error) {
      this.logger.error(`Error processing ${aggregator} webhook: ${error.message}`, error.stack);
      throw error;
    }
  }

  /**
   * Normalizes various aggregator payloads into a common PaySurityOrder format.
   * This is a simplified example; real-world scenarios would involve more complex mapping.
   */
  private normalizeOrder(
    aggregator: string,
    payload: any,
    tenantId: string,
    merchantId: string,
  ): PaySurityOrder {
    let order: PaySurityOrder;

    switch (aggregator.toLowerCase()) {
      case 'doordash':
        order = this.normalizeDoorDashOrder(payload, tenantId, merchantId);
        break;
      case 'ubereats':
        order = this.normalizeUberEatsOrder(payload, tenantId, merchantId);
        break;
      case 'grubhub':
        order = this.normalizeGrubHubOrder(payload, tenantId, merchantId);
        break;
      default:
        throw new Error(`Unsupported aggregator: ${aggregator}`);
    }

    // Ensure rawPayload is always included for auditing
    order.rawPayload = sanitizeGatewayResponse(payload);
    order.aggregator = aggregator; // Ensure aggregator is set consistently

    return order;
  }

  private normalizeDoorDashOrder(payload: any, tenantId: string, merchantId: string): PaySurityOrder {
    const totalAmountCents = Math.round(parseFloat(payload.total_amount_cents) || 0);
    const items: PaySurityOrderItem[] =
      payload.items?.map((item: any) => ({
        tenantId: tenantId,
        name: item.name,
        quantity: item.quantity,
        unitPriceCents: Math.round(parseFloat(item.unit_price_cents) || 0),
        totalPriceCents: Math.round(parseFloat(item.total_price_cents) || 0),
      })) || [];

    let status: PaySurityOrder['status'];
    switch (payload.status) {
      case 'ORDER_PENDING':
        status = 'PENDING';
        break;
      case 'ORDER_ACCEPTED':
        status = 'ACCEPTED';
        break;
      case 'ORDER_CANCELLED':
        status = 'CANCELLED';
        break;
      case 'ORDER_DELIVERED':
        status = 'DELIVERED';
        break;
      default:
        status = 'UNKNOWN';
    }

    return {
      tenantId,
      merchantId,
      externalOrderId: payload.external_order_id.toString(),
      aggregator: 'DoorDash',
      status,
      totalAmountCents,
      currency: payload.currency || 'USD',
      rawPayload: payload,
      items,
    };
  }

  private normalizeUberEatsOrder(payload: any, tenantId: string, merchantId: string): PaySurityOrder {
    const totalAmountCents = Math.round(parseFloat(payload.total?.amount) * 100 || 0);
    const items: PaySurityOrderItem[] =
      payload.items?.map((item: any) => ({
        tenantId: tenantId,
        name: item.title,
        quantity: item.quantity,
        unitPriceCents: Math.round(parseFloat(item.price_info?.base_price?.amount) * 100 || 0),
        totalPriceCents: Math.round(parseFloat(item.price_info?.total_price?.amount) * 100 || 0),
      })) || [];

    let status: PaySurityOrder['status'];
    switch (payload.current_state) {
      case 'CREATED':
      case 'ACCEPTED':
        status = 'ACCEPTED'; // UberEats combines these
        break;
      case 'CANCELED':
        status = 'CANCELLED';
        break;
      case 'DELIVERED':
        status = 'DELIVERED';
        break;
      default:
        status = 'UNKNOWN';
    }

    return {
      tenantId,
      merchantId,
      externalOrderId: payload.order_id.toString(),
      aggregator: 'UberEats',
      status,
      totalAmountCents,
      currency: payload.total?.currency_code || 'USD',
      rawPayload: payload,
      items,
    };
  }

  private normalizeGrubHubOrder(payload: any, tenantId: string, merchantId: string): PaySurityOrder {
    const totalAmountCents = Math.round(parseFloat(payload.order?.price?.total) * 100 || 0);
    const items: PaySurityOrderItem[] =
      payload.order?.items?.map((item: any) => ({
        tenantId: tenantId,
        name: item.name,
        quantity: item.quantity,
        unitPriceCents: Math.round(parseFloat(item.price?.unit_price) * 100 || 0),
        totalPriceCents: Math.round(parseFloat(item.price?.total_price) * 100 || 0),
      })) || [];

    let status: PaySurityOrder['status'];
    switch (payload.order?.status) {
      case 'NEW':
      case 'CONFIRMED':
        status = 'ACCEPTED';
        break;
      case 'CANCELED':
        status = 'CANCELLED';
        break;
      case 'DELIVERED':
        status = 'DELIVERED';
        break;
      default:
        status = 'UNKNOWN';
    }

    return {
      tenantId,
      merchantId,
      externalOrderId: payload.order_id.toString(),
      aggregator: 'GrubHub',
      status,
      totalAmountCents,
      currency: payload.order?.price?.currency || 'USD',
      rawPayload: payload,
      items,
    };
  }

  /**
   * Checks if an order with the given external ID and aggregator already exists.
   * @returns The existing order's details if found, otherwise null.
   */
  private async findExistingOrder(
    externalOrderId: string,
    aggregator: string,
    tenantId: string,
  ): Promise<{ id: string; status: PaySurityOrder['status']; totalAmountCents: number; merchantId: string } | null> {
    try {
      const result = await (this.db as any).execute(sql`
        SELECT
            id,
            status,
            total_amount_cents AS "totalAmountCents",
            merchant_id AS "merchantId"
        FROM orders
        WHERE external_order_id = ${externalOrderId}
          AND aggregator = ${aggregator}
          AND tenant_id = ${tenantId};
      `);

      if (result && result.length > 0) {
        const orderRow = result[0];
        return {
          id: orderRow.id,
          status: orderRow.status as PaySurityOrder['status'],
          totalAmountCents: orderRow.totalAmountCents,
          merchantId: orderRow.merchantId,
        };
      }
      return null;
    } catch (error) {
      this.logger.error(`Error finding existing order: ${error.message}`, error.stack);
      throw error;
    }
  }

  /**
   * Creates a new order and its associated items.
   * Uses a database transaction for atomicity.
   */
  private async createOrder(order: PaySurityOrder): Promise<string> {
    try {
      let newOrderId: string;

      await (this.db as any).transaction(async (tx) => {
        // Insert the main order
        // The `id` column is expected to have a DEFAULT gen_random_uuid() for automatic ID generation.
        const [insertedOrder] = await tx.execute(sql`
          INSERT INTO orders (
              tenant_id, merchant_id, aggregator, external_order_id,
              status, total_amount_cents, currency, raw_payload, created_at, updated_at
          ) VALUES (
              ${order.tenantId}, ${order.merchantId}, ${order.aggregator}, ${order.externalOrderId},
              ${order.status}, ${order.totalAmountCents}, ${order.currency}, ${JSON.stringify(order.rawPayload)}::jsonb, NOW(), NOW()
          ) RETURNING id;
        `);
        newOrderId = insertedOrder.id;

        // Insert order items
        if (order.items && order.items.length > 0) {
          const itemInsertPromises = order.items.map((item) =>
            tx.execute(sql`
              INSERT INTO order_items (
                  order_id, tenant_id, name, quantity, unit_price_cents, total_price_cents
              ) VALUES (
                  ${newOrderId}, ${item.tenantId}, ${item.name}, ${item.quantity}, ${item.unitPriceCents}, ${item.totalPriceCents}
              );
            `)
          );
          await Promise.all(itemInsertPromises);
        }
      });

      return newOrderId;
    } catch (error) {
      this.logger.error(`Error creating new order: ${error.message}`, error.stack);
      throw error;
    }
  }

  /**
   * Updates an existing order's status and raw payload.
   */
  private async updateOrderStatus(
    orderId: string,
    newStatus: PaySurityOrder['status'],
    rawPayload: any,
    tenantId: string,
  ): Promise<void> {
    try {
      await (this.db as any).execute(sql`
        UPDATE orders
        SET
            status = ${newStatus},
            updated_at = NOW(),
            raw_payload = ${JSON.stringify(rawPayload)}::jsonb
        WHERE id = ${orderId} AND tenant_id = ${tenantId};
      `);
      this.logger.log(`Order ${orderId} status updated to ${newStatus}.`);
    } catch (error) {
      this.logger.error(`Error updating order ${orderId} status: ${error.message}`, error.stack);
      throw error;
    }
  }

  /**
   * Handles cancellation webhooks from aggregators.
   */
  async handleCancellation(
    aggregator: string,
    externalOrderId: string,
    tenantId: string,
    merchantId: string,
    payload: any,
  ): Promise<void> {
    this.logger.log(
      `Handling cancellation for external order ${externalOrderId} from ${aggregator} for tenant ${tenantId}.`,
    );
    try {
      const existingOrder = await this.findExistingOrder(externalOrderId, aggregator, tenantId);

      if (!existingOrder) {
        this.logger.warn(`Cancellation received for non-existent order ${externalOrderId}. Skipping.`);
        return;
      }

      if (existingOrder.status === 'CANCELLED') {
        this.logger.log(`Order ${existingOrder.id} is already cancelled. No action needed.`);
        return;
      }

      await this.updateOrderStatus(existingOrder.id, 'CANCELLED', payload, tenantId);
      (this.eventBusService as any).emit('order.status.updated', {
        orderId: existingOrder.id,
        tenantId,
        merchantId,
        oldStatus: existingOrder.status,
        newStatus: 'CANCELLED',
        externalOrderId,
      });
      this.logger.log(`Order ${existingOrder.id} successfully cancelled.`);
    } catch (error) {
      this.logger.error(`Error handling cancellation for order ${externalOrderId}: ${error.message}`, error.stack);
      throw error;
    }
  }

  /**
   * Synchronizes order status with external aggregator system.
   * This would typically be called by a cron job or an external trigger.
   */
  async syncOrderStatus(orderId: string, tenantId: string): Promise<void> {
    this.logger.log(`Syncing status for order ${orderId} for tenant ${tenantId}.`);
    try {
      const orderDetails = await this.getInternalOrderDetails(orderId, tenantId);

      if (!orderDetails) {
        this.logger.warn(`Order ${orderId} not found for status sync.`);
        return;
      }

      let externalStatus: PaySurityOrder['status'] = 'UNKNOWN';
      let externalPayload: any = {};

      // Simulate API call to aggregator
      switch (orderDetails.aggregator.toLowerCase()) {
        case 'doordash':
          ({ status: externalStatus, payload: externalPayload } = await (this as any).fetchDoorDashOrderStatus(
            orderDetails.externalOrderId,
            tenantId,
          ));
          break;
        case 'ubereats':
          ({ status: externalStatus, payload: externalPayload } = await (this as any).fetchUberEatsOrderStatus(
            orderDetails.externalOrderId,
            tenantId,
          ));
          break;
        case 'grubhub':
          ({ status: externalStatus, payload: externalPayload } = await (this as any).fetchGrubHubOrderStatus(
            orderDetails.externalOrderId,
            tenantId,
          ));
          break;
        default:
          this.logger.warn(`Unsupported aggregator for status sync: ${orderDetails.aggregator}`);
          return;
      }

      if (externalStatus && externalStatus !== orderDetails.status) {
        this.logger.log(
          `Status mismatch for order ${orderId}: internal=${orderDetails.status}, external=${externalStatus}. Updating...`,
        );
        await this.updateOrderStatus(orderId, externalStatus, externalPayload, tenantId);
        (this.eventBusService as any).emit('order.status.updated', {
          orderId: orderId,
          tenantId: tenantId,
          merchantId: orderDetails.merchantId,
          oldStatus: orderDetails.status,
          newStatus: externalStatus,
          externalOrderId: orderDetails.externalOrderId,
        });
      } else {
        this.logger.log(`Order ${orderId} status is already in sync or no change detected.`);
      }
    } catch (error) {
      this.logger.error(`Error syncing status for order ${orderId}: ${error.message}`, error.stack);
    }
  }

  /**
   * Helper to retrieve internal order details for status sync.
   */
  private async getInternalOrderDetails(
    orderId: string,
    tenantId: string,
  ): Promise<{ externalOrderId: string; aggregator: string; status: PaySurityOrder['status']; merchantId: string } | null> {
    try {
      const result = await (this.db as any).execute(sql`
        SELECT
            external_order_id AS "externalOrderId",
            aggregator,
            status,
            merchant_id AS "merchantId"
        FROM orders
        WHERE id = ${orderId} AND tenant_id = ${tenantId};
      `);

      if (result && result.length > 0) {
        const orderRow = result[0];
        return {
          externalOrderId: orderRow.externalOrderId,
          aggregator: orderRow.aggregator,
          status: orderRow.status as PaySurityOrder['status'],
          merchantId: orderRow.merchantId,
        };
      }
      return null;
    } catch (error) {
      this.logger.error(`Error fetching internal order details for ${orderId}: ${error.message}`, error.stack);
      throw error;
    }
  }
}


