import { Injectable, Inject, Logger } from '@nestjs/common';
import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { eq, and, desc, sql } from 'drizzle-orm';
import { auditLogs } from '@paysurity/database'; type NewAuditLog = any; type AuditLog = any;

@Injectable()
export class AuditLogService {
  private readonly logger = new Logger(AuditLogService.name);

  constructor(@Inject('DATABASE') private db: NodePgDatabase<any>) {}

  /**
   * Creates a new audit log entry.
   *
   * @param logData The data for the new audit log. `id` and `createdAt` are typically
   *                generated by the database and should not be provided here.
   * @returns The created audit log entry, or null if the creation failed.
   */
  async createLog(
    logData: Omit<NewAuditLog, 'id' | 'createdAt'>,
  ): Promise<AuditLog | null> {
    try {
      const [newAuditLog] = (await (this.db as any)
        .insert(auditLogs)
        .values(logData) // `createdAt` should be handled by the database's default value
        .returning() as any);

      if (!newAuditLog) {
        this.logger.error('Failed to create audit log: insert operation returned no data.');
        return null;
      }
      return newAuditLog;
    } catch (error) {
      this.logger.error(`Error creating audit log: ${error.message}`, error.stack);
      throw new Error('Failed to create audit log.');
    }
  }

  /**
   * Retrieves audit logs based on provided filters and pagination options.
   *
   * @param options Filtering and pagination options.
   * @returns An array of audit log entries matching the criteria.
   */
  async getLogs(options?: {
    userId?: string;
    action?: string;
    resourceType?: string;
    resourceId?: string;
    ipAddress?: string;
    userAgent?: string;
    startDate?: Date;
    endDate?: Date;
    limit?: number;
    offset?: number;
  }): Promise<AuditLog[]> {
    try {
      const {
        userId,
        action,
        resourceType,
        resourceId,
        ipAddress,
        userAgent,
        startDate,
        endDate,
        limit = 100, // Default limit
        offset = 0, // Default offset
      } = options || {};

      const conditions = [];

      if (userId) {
        conditions.push(eq(auditLogs.userId, userId));
      }
      if (action) {
        conditions.push(eq(auditLogs.action, action));
      }
      if (resourceType) {
        conditions.push(eq(auditLogs.resourceType, resourceType));
      }
      if (resourceId) {
        conditions.push(eq(auditLogs.resourceId, resourceId));
      }
      if (ipAddress) {
        conditions.push(eq(auditLogs.ipAddress, ipAddress));
      }
      if (userAgent) {
        // For partial case-insensitive search, consider using `ilike` if supported or `sql` directly
        conditions.push(eq(auditLogs.userAgent, userAgent)); // Exact match for now
      }
      if (startDate) {
        conditions.push(sql`${auditLogs.createdAt} >= ${startDate.toISOString()}`);
      }
      if (endDate) {
        conditions.push(sql`${auditLogs.createdAt} <= ${endDate.toISOString()}`);
      }

      const query = this.db
        .select()
        .from(auditLogs)
        .where(conditions.length ? and(...conditions) : undefined)
        .orderBy(desc(auditLogs.createdAt))
        .limit(limit)
        .offset(offset);

      return await query;
    } catch (error) {
      this.logger.error(`Error retrieving audit logs: ${error.message}`, error.stack);
      throw new Error('Failed to retrieve audit logs.');
    }
  }

  /**
   * Retrieves a single audit log entry by its unique ID.
   *
   * @param id The ID of the audit log to retrieve.
   * @returns The audit log entry if found, otherwise `undefined`.
   */
  async getLogById(id: string): Promise<AuditLog | undefined> {
    try {
      const [auditLog] = await this.db
        .select()
        .from(auditLogs)
        .where(eq(auditLogs.id, id));

      return auditLog;
    } catch (error) {
      this.logger.error(`Error retrieving audit log by ID ${id}: ${error.message}`, error.stack);
      throw new Error('Failed to retrieve audit log by ID.');
    }
  }
}



